//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ShortBus.SQLStore
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ServiceBusModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ServiceBusModelContainer object using the connection string found in the 'ServiceBusModelContainer' section of the application configuration file.
        /// </summary>
        public ServiceBusModelContainer() : base("name=ServiceBusModelContainer", "ServiceBusModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ServiceBusModelContainer object.
        /// </summary>
        public ServiceBusModelContainer(string connectionString) : base(connectionString, "ServiceBusModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ServiceBusModelContainer object.
        /// </summary>
        public ServiceBusModelContainer(EntityConnection connection) : base(connection, "ServiceBusModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Subscriber> Subscribers
        {
            get
            {
                if ((_Subscribers == null))
                {
                    _Subscribers = base.CreateObjectSet<Subscriber>("Subscribers");
                }
                return _Subscribers;
            }
        }
        private ObjectSet<Subscriber> _Subscribers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Subscribers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubscribers(Subscriber subscriber)
        {
            base.AddObject("Subscribers", subscriber);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ServiceBusModel", Name="Subscriber")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Subscriber : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Subscriber object.
        /// </summary>
        /// <param name="subscriber1">Initial value of the subscriber property.</param>
        /// <param name="endpoint">Initial value of the endpoint property.</param>
        /// <param name="last_seen">Initial value of the last_seen property.</param>
        public static Subscriber CreateSubscriber(global::System.Guid subscriber1, global::System.String endpoint, global::System.DateTime last_seen)
        {
            Subscriber subscriber = new Subscriber();
            subscriber.subscriber = subscriber1;
            subscriber.endpoint = endpoint;
            subscriber.last_seen = last_seen;
            return subscriber;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid subscriber
        {
            get
            {
                return _subscriber;
            }
            set
            {
                if (_subscriber != value)
                {
                    OnsubscriberChanging(value);
                    ReportPropertyChanging("subscriber");
                    _subscriber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("subscriber");
                    OnsubscriberChanged();
                }
            }
        }
        private global::System.Guid _subscriber;
        partial void OnsubscriberChanging(global::System.Guid value);
        partial void OnsubscriberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String endpoint
        {
            get
            {
                return _endpoint;
            }
            set
            {
                OnendpointChanging(value);
                ReportPropertyChanging("endpoint");
                _endpoint = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("endpoint");
                OnendpointChanged();
            }
        }
        private global::System.String _endpoint;
        partial void OnendpointChanging(global::System.String value);
        partial void OnendpointChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime last_seen
        {
            get
            {
                return _last_seen;
            }
            set
            {
                Onlast_seenChanging(value);
                ReportPropertyChanging("last_seen");
                _last_seen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("last_seen");
                Onlast_seenChanged();
            }
        }
        private global::System.DateTime _last_seen;
        partial void Onlast_seenChanging(global::System.DateTime value);
        partial void Onlast_seenChanged();

        #endregion
    
    }

    #endregion
    
}
